services:
  db-postgres:
    image: postgres:15
    container_name: db-postgres
    environment:
      POSTGRES_USER: iouri
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ressources
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - lab_net

  docker-pool-1:
    image: ubuntu:22.04
    container_name: docker-pool-1
    command: sleep infinity
    restart: always
    networks:
      - lab_net

  docker-pool-2:
    image: ubuntu:22.04
    container_name: docker-pool-2
    command: sleep infinity
    restart: always
    networks:
      - lab_net

  docker-pool-3:
    image: ubuntu:22.04
    container_name: docker-pool-3
    command: sleep infinity
    restart: always
    networks:
      - lab_net

volumes:
  db_data:

networks:
  lab_net:
    external: true
